# en_us.py

translations = {
    "preview.button.clear_all": "Clear All",
    "preview.confirm.clear_all.title": "Confirm Clear",
    "preview.confirm.clear_all.message": "Are you sure you want to delete all {count} generated media files and clear the list? This action cannot be undone.",
    "log.session_data_loaded": "{count} items from the previous session were loaded.",
    "tab.preview.title": "Preview",
    "preview.group.file_list.title": "Generated Files",
    "preview.button.refresh": "Refresh List",
    "preview.group.player.title": "Player",
    "preview.label.subtitle": "Subtitle:",
    "preview.info.no_items": "No media items have been generated yet.",
    "preview.info.click_item": "Click an item in the list to preview.",
    "preview.action.delete": "Delete",
    "preview.speed.slow": "0.5x",
    "preview.speed.normal": "1x (Normal)",
    "preview.speed.fast": "1.5x",
    "preview.speed.very_fast": "2x",
    "preview.checkbox.show_translation": "Show Translation",
    "tab.subs_and_time.title": "Subtitles and Time",
    "process.group.generation.title": "Generate Subtitles (with Online API)",
    "process.info.api_key_instructions": 'Create a free account at <a href="https://www.assemblyai.com/">AssemblyAI</a> and get your API key from <a href="https://www.assemblyai.com/dashboard/api-keys">your dashboard</a>.',
    "process.button.generate_subs": "Generate Subtitles from Audio/Video",
    "process.label.transcription_language": "Subtitle Language:",
    "process.label.api_key": "API Key (AssemblyAI):",
    "process.placeholder.api_key": "Paste your free API key here",
    "process.error.api_key_needed": "Please enter an API key to use the online subtitle generation.",
    "process.error.media_file_needed_for_generation": "Select a media file first to generate subtitles.",
    "process.warning.generation_running": "Subtitle generation process already running.",
    "process.log.generation_started": "Starting subtitle generation with online API. This may take a while.",
    "process.status.generating_stopping": "Stop requested for generation...",
    "process.group.translation.title": "Translate Subtitles (with Online API)",
    "process.button.translate_subs": "Translate Main Subtitle",
    "process.label.translation_language": "Target Language:",
    "process.error.no_subs_to_translate": "Load a main subtitle first to translate.",
    "process.log.translation_started": "Starting subtitle translation. This may take a while.",
    "transcription.starting_status": "Starting online subtitle generation...",
    "transcription.uploading": "Uploading media file to API...",
    "transcription.transcribing": "API is transcribing audio... Please wait.",
    "transcription.polling": "Polling for API results...",
    "transcription.interrupted_log": "Subtitle generation interrupted.",
    "transcription.error_log": "ERROR generating subtitles online: {error}",
    "transcription.finalize_prefix": "Subtitle generation {status}.",
    "transcription.finalize_showInfo_success": "{prefix}\nSubtitle file generated and loaded:\n{path}",
    "transcription.finalize_showInfo_fail": "{prefix}\nNo subtitle file was generated.",
    "translation.performing": "Translating item {current}/{total}...",
    "translation.finalize_prefix": "Translation {status}.",
    "translation.finalize_showInfo_success": "{prefix}\nTranslated subtitle file generated and loaded:\n{path}",
    "translation.finalize_showInfo_fail": "{prefix}\nNo translated subtitle file was generated.",
    "dialog.title": "Advanced Media Splitter ({addon_name})",
    "dialog.language_label": "Language:",
    "tab.process.title": "Input and Processing",
    "tab.images.title": "Generate Images from Videos",
    "tab.anki_export.title": "Anki Export",

    "tab.downloader.title": "Media Downloader",

    "process.group.files.title": "Input and Output Files",
    "process.label.media_file": "Media File (Audio/Video):",
    "process.placeholder.media_file": "Path to the audio or video file",
    "process.button.open_media": "Open Media",
    "process.label.main_subtitle": "Subtitle (SRT, VTT, etc.):",
    "process.placeholder.main_subtitle": "Path to the subtitle file",
    "process.button.open_subtitle": "Open Subtitle",
    "process.label.translation_subtitle": "Translation (Subtitle - Optional):",
    "process.placeholder.translation_subtitle": "Path to the translation subtitle file",
    "process.button.open_translation": "Open Translation",
    "process.label.output_folder_media": "Output Folder (processed media):",
    "process.button.select_output_folder": "Select Folder",
    "process.checkbox.direct_to_collection_media": "Send directly to Anki's collection.media",
    "process.label.output_format": "Output Format:",
    "process.format.mp3": "MP3 (audio)",
    "process.format.mp4": "MP4 (video)",
    "process.format.webm": "WebM (video)",
    "process.group.offset.title": "Time Adjustment (Main Subtitle)",
    "process.label.offset_seconds": "Seconds (e.g., 0.5 for forward, -0.3 for backward):",
    "process.button.apply_offset_save_srt": "Apply Adjustment and Save Subtitle",
    "process.group.time_limit.title": "Limit by Subtitles (Optional)",
    "process.checkbox.limit_time_range": "Limit processing to a time range",
    "process.label.time_limit_from": "From:",
    "process.label.time_limit_to": "To:",
    "process.placeholder.time_limit": "HH:MM:SS",
    "process.log.time_limit_applied": "INFO: Time limit applied. Processing {count} of {total} subtitles in the range from {start} to {end}.",
    "process.group.single_clip.title": "Single Clip (with Subtitle)",
    "process.button.single_clip": "Cut and Save Clip",
    "process.log.single_clip_started": "Starting single clip cut for file '{filename}'...",
    "process.log.single_clip_success": "SUCCESS: Single clip saved to '{path}'.",
    "process.log.single_clip_and_srt_success": "SUCCESS: Single clip and corresponding subtitle saved to '{path}'.",
    "process.log.single_clip_srt_error": "WARNING: Video clip was saved, but failed to create the subtitle file: {error}",
    "process.log.single_clip_error": "ERROR creating single clip for '{filename}'. FFmpeg stderr: {stderr}",
    "process.error.invalid_time_range": "Invalid time range. The end time must be greater than the start time.",
    "process.group.main_processing.title": "Main Processing (Split Media)",
    "process.checkbox.adjust_cuts_to_silence": "Adjust cuts to audio pauses (more precise)",
    "process.log.silence_detection_started": "Starting silence detection in audio. This may take a moment...",
    "process.log.silence_detection_finished": "Silence detection finished. {count} pauses found.",
    "process.log.silence_detection_failed": "WARNING: Silence detection failed. Cuts will be made at the exact subtitle times. Error: {error}",
    "process.button.split_media": "Split Media by Subtitles",
    "process.button.stop_processing": "Stop Process",
    "process.label.time_remaining_prefix": "Time remaining:",
    "process.label.status_ready": "Ready.",
    "process.label.status_calculating": "Calculating...",
    "process.group.log.title": "Detailed Log (Media Processing)",
    "process.info.ffmpeg_not_found": "FFmpeg not found. Please check the installation or allow the addon to download it.",
    "process.warning.process_running": "Splitting process is already running.",
    "process.error.invalid_media_file": "Invalid media file.",
    "process.error.no_main_subtitle": "No main subtitle loaded.",
    "process.error.output_folder_invalid": "Output folder is invalid or could not be created:\n{path}\nError: {error}",
    "process.log.using_default_output_folder": "Output folder not set, using default: {path}",
    "process.log.split_started": "Starting media split (format: {format}). Total of {count} items.",
    "process.status.stopping": "Stop requested...",
    "process.dialog.offset_srt.no_subs_loaded": "No main subtitle loaded.",
    "process.dialog.offset_srt.invalid_offset_value": "Invalid adjustment seconds.",
    "process.dialog.offset_srt.output_folder_needed": "Set an output folder first (in the 'Input and Processing' tab).",
    "process.dialog.offset_srt.error_creating_folder": "Output folder for adjusted subtitle is invalid or could not be created:\n{path}\nError: {error}",
    "process.dialog.offset_srt.success_title": "Adjustment Saved",
    "process.dialog.offset_srt.success_message": "Main subtitles {action_desc} and saved to:\n{path}",
    "process.dialog.offset_srt.action_unchanged": "unchanged",
    "process.dialog.offset_srt.action_advanced": "advanced",
    "process.dialog.offset_srt.action_delayed": "delayed",
    "process.dialog.offset_srt.error_saving_title": "Error Saving Adjusted Subtitle",
    "process.dialog.offset_srt.error_saving_message": "Could not save the subtitle file: {error}",
    "process.dialog.offset_srt.log_saving_to_original_folder": "Adjusted subtitle will be saved in the original subtitle's folder: {path}",
    "process.dialog.offset_srt.log_suffix_original_srt_undefined_fallback": " (for the adjusted subtitle, as the original subtitle was not defined or was invalid).",
    "process.dialog.offset_srt.log_fallback_to_main_output": "The original subtitle is not loaded or is invalid. The adjusted subtitle will be saved in the main output folder: {path}",
    "process.dialog.offset_srt.info_fallback_to_main_output": "The original subtitle is not loaded or its file path is invalid.\nThe adjusted subtitle file will be saved in the main output folder:\n{path}",
    "process_starting_status": "Starting processing...",
    "preparing_items_status": "Preparing {count} items...",
    "split_interrupted_log": "Split interrupted.",
    "processing_item_status": "Processing {current}/{total} (ID:{id}) - {percent}%",
    "skipped_item_log": "WARNING: ID {id} skipped (no text or invalid time).",
    "reencoding_to_mp4_log": "INFO: Re-encoding to MP4 (ID {id}): {filename}",
    "reencoding_to_webm_log": "INFO: Re-encoding to WebM (ID {id}): {filename}",
    "unsupported_ext_for_split_log": "ERROR: Unsupported file extension for splitting: {ext}",
    "file_created_success_log": "SUCCESS: {filename} created.",
    "file_and_srt_created_success_log": "SUCCESS: {filename} and .srt subtitle created.",
    "process.log.srt_creation_failed": "WARNING: Media file created, but failed to save .srt subtitle for ID {id}: {error}",
    "ffmpeg_error_log": "FFmpeg ERROR (ID {id}, {ext}): {filename}. Stderr: {stderr}",
    "ffmpeg_reencode_fail_warning_log": "WARNING: Failed to re-encode to {ext} (ID {id}). The original file may have issues or incompatible codecs.",
    "ffmpeg_general_error_log": "General FFmpeg ERROR (ID {id}, {ext}): {error}",
    "split_finalize_prefix": "Split {status}.",
    "files_created_log_suffix": "{count} media files created.",
    "split_finalize_detailed_status": "{prefix} {files_count} files. {items_attempted}/{total_initial} processed ({percent}%).",
    "split_finalize_all_created_status": "{prefix} All {count} files created (100%).",
    "split_finalize_showInfo_success": "{prefix}\n{count} files in:\n{path}",
    "split_finalize_showInfo_no_files": "{prefix}\nNo media files created.",
    "applying_offset_log": "Applying offset of {offset_s}s ({offset_ms}ms) to the main subtitle.",
    "adjusted_subs_default_filename_stem": "adjusted_subtitles",
    "subs_filename_suffix": "subtitles",
    "adjusted_srt_filename_suffix": "adjusted",
    "adjusted_subs_saved_log": "Adjusted main subtitles saved to: {path}",
    "images.group.title": "Generate Images",
    "images.group.from_source.title": "Method 1: From Original Video (Fast & Recommended)",
    "images.info.generate_from_source": "This method uses the main video file from the 'Input' tab and the loaded subtitles to quickly generate an image for each subtitle entry. It's the most efficient way if you need both audio (MP3) and images.",
    "images.button.generate_from_source": "Generate Images from Original Video",
    "images.group.from_split_videos.title": "Method 2: From Split Video Clips",
    "images.info.source_videos_intro": "This method uses the videos (.mp4, .webm) already generated in the 'Input and Processing' tab to create .jpg images.",
    "images.info.output_destination_prefix": "The generated images will be saved in:",
    "images.checkbox.direct_to_collection_media": "Send generated images directly to Anki's collection.media",
    "images.button.convert_videos": "Convert Split Videos to Images",
    "images.button.stop_conversion": "Stop Image Generation",
    "images.label.status_ready": "Ready.",
    "images.group.log.title": "Detailed Log (Image Generation)",
    "images.log.using_default_media_folder": "Media output folder not set, using default: {path}",
    "images.error.media_folder_invalid": "The media output folder '{path}' is invalid.",
    "images.info.no_videos_found": "No .mp4 or .webm video files found in the folder '{path}' to convert.",
    "images.info.no_subtitles_data_for_videos": "No data from the 'Input and Processing' tab found. Process media first to generate videos.",
    "images.info.no_valid_videos_from_processing": "No valid .mp4 or .webm video files were found {source} to convert.",
    "images.source_description.processed_items": "from the items processed in the first tab",
    "images.error.cannot_create_images_folder": "Could not create/access the images folder '{path}': {error}",
    "images.log.conversion_started": "Starting conversion of {count} videos to .jpg images in {path}.",
    "images.log.conversion_started_from_processed": "Starting conversion of {count} videos (from the processing tab) to .jpg images in {path}.",
    "images.log.generation_from_source_started": "Starting image generation from source video for {count} subtitles.",
    "images.status.stopping": "Stop requested...",
    "images.finalize.info_success": "{status_text}\nSaved in: {path}",
    "images.finalize.info_no_images": "{status_text}\nNo images were generated.",
    "image_conversion_starting_status": "Starting image generation...",
    "preparing_videos_status": "Preparing {count} videos...",
    "preparing_subtitles_status": "Preparing {count} subtitles for image generation...",
    "image_conversion_interrupted_log": "Image generation interrupted.",
    "converting_video_status": "Converting {filename} ({current}/{total})",
    "generating_image_from_source_status": "Generating image for subtitle {current}/{total}",
    "image_created_success_log": "SUCCESS: Image '{filename}' created.",
    "ffmpeg_run_but_image_not_created_log": "ERROR: FFmpeg ran, but '{filename}' was not created or is empty.",
    "ffmpeg_error_converting_image_log": "FFmpeg ERROR converting '{filename}'",
    "general_error_converting_image_log": "General ERROR converting '{filename}': {error}",
    "image_conversion_finalize_prefix": "Image generation {status}.",
    "image_conversion_finalize_log": "{prefix} {created_count}/{total_count} images generated.",
    "image_conversion_finalize_status_ui": "{prefix} {count} images generated.",
    "anki_export.group.title": "Anki Export Options",
    "anki_export.label.deck": "Deck:",
    "anki_export.label.note_type": "Note Type:",
    "anki_export.label.media_field": "Media Field (Audio/Video):",
    "anki_export.label.subtitle_field": "Main Subtitle Field:",
    "anki_export.label.translation_field": "Translation Field:",
    "anki_export.label.image_field": "Image Field:",
    "anki_export.checkbox.use_external_folder": "Use files from a specific folder (if unchecked, uses current session's)",
    "anki_export.group.media_files_anki.title": "Media Files for Anki Export",
    "anki_export.group.source_files.title": "Source of Files",
    "anki_export.radio.use_session_files": "Use files from the current session (default)",
    "anki_export.radio.use_external_folder": "Use external folder",
    "anki_export.label.source_folder": "Source Folder:",
    "anki_export.placeholder.source_folder": "Defaults to processed files from this session",
    "anki_export.button.select_source_folder": "Select Folder...",
    "anki_export.button.clear_source_folder": "Clear",
    "anki_export.button.list_media_files": "List Media Files from Source",
    "anki_export.button.add_to_anki": "Add Listed Items to Anki",
    "anki_export.log.media_folder_not_defined": "Media output folder not defined.",
    "anki_export.log.media_folder_invalid": "Media folder '{path}' is not valid.",
    "anki_export.log.no_media_files_found": "No media files (.mp3, .mp4, .webm) found in:\n{path}",
    "anki_export.log.files_listed_for_export": "{count} media files listed for Anki export from '{source}'.",
    "anki_export.log.source.session": "current session",
    "anki_export.log.source.folder": "selected folder",
    "anki_export.error.anki_collection_unavailable": "Anki collection not available.",
    "anki_export.error.missing_selections": "Please select Deck, Note Type, Media Field, and Main Subtitle Field.",
    "anki_export.error.note_type_not_found": "Note Type ID {model_id} not found.",
    "anki_export.error.field_not_in_model": "The {field_desc} field '{field_name}' does not exist in the Note Type '{model_name}'.",
    "anki_export.error.field_desc.media": "Media",
    "anki_export.error.field_desc.main_subtitle": "Main Subtitle",
    "anki_export.error.field_desc.translation": "Translation",
    "anki_export.error.field_desc.image": "Image",
    "anki_export.error.field_not_selected": "{field_desc} field not selected.",
    "anki_export.confirm.combined_fields_title": "Combined Fields",
    "anki_export.confirm.combined_fields_message": "Some selected fields are the same. The content will be combined in those fields using '<br>' as a separator. Continue?",
    "anki_export.progress.adding_notes": "Adding notes to Anki...",
    "anki_export.progress.adding_note_item": "Adding {current}/{total}: {filename}",
    "anki_export.info.notes_added_success": "{count} notes added to '{deck_name}'.",
    "anki_export.info.no_notes_added": "No notes were added. Check the log.",
    "anki_export.info.addition_cancelled": "Addition cancelled. {count} notes were added before.",
    "anki_export.log.completed_anki_add": "Completed adding to Anki: {count} notes.",
    "anki_export.log.no_processed_items_for_export": "No processed media items (from the current subtitles) available for export.",
    "anki_export.info.no_processed_items_for_export_title": "No Items to Export",
    "anki_export.warning.no_subtitles_loaded_for_export": "No main subtitles loaded. There are no items to process for export.",
    "anki_export.log.no_subtitles_loaded_for_listing": "No subtitles loaded to list processed media files.",
    "anki_export.log.no_media_files_processed_in_session": "No media files generated/processed in the current session.",
    "anki_export.log.processed_media_files_header": "Media files processed in the current session (in: {folder_path}, {count} items):\n",
    "failed_to_copy_main_media_log": "Failed to copy main media to Anki: {filename}",
    "error_adding_main_media_log": "Error adding main media '{filename}':{error}",
    "failed_to_copy_image_log": "Failed to copy image to Anki: {filename}",
    "error_adding_image_log": "Error adding image '{filename}': {error}",
    "error_adding_note_log": "Error adding note for '{filename}':{error}",
    "error_cleaning_orphan_media_log": "Error cleaning orphan media '{filename}': {error}",
    "error_cleaning_orphan_image_log": "Error cleaning orphan image '{filename}': {error}",
    "media_files_in_folder_log_header": "Media files in {path} ({count} items):\n",
    "ffmpeg.ask_download_title": "FFmpeg Not Found",
    "ffmpeg.ask_download_message": (
        "<p>{us_flag_html}FFmpeg was not found on your system or in this addon's folder.<br>"
        "It is essential for processing audio and video files.</p>"
        "<p>{us_flag_html}Do you want to automatically download and install FFmpeg (~80MB) into this addon's folder?<br>"
        "(Recommended for Windows users. Linux/macOS users usually install it via their system's package manager.)</p>"
    ),
    "ffmpeg.download_cancelled_message_addon": (
        "<p>{us_flag_html}FFmpeg download cancelled by user. Media processing features may not be available or may fail.</p>"
    ),
    "ffmpeg.downloading_message": "Downloading FFmpeg...",
    "ffmpeg.download_progress_label": "Downloading FFmpeg: {percent}%",
    "ffmpeg.download_cancelled_by_user": "FFmpeg download cancelled by user.",
    "ffmpeg.download_failed_with_error": "FFmpeg download failed: {error}",
    "ffmpeg.extracting_message": "FFmpeg downloaded. Extracting and setting up...",
    "ffmpeg.extraction_failed": "Failed to extract FFmpeg: {error}",
    "ffmpeg.install_success_message": "FFmpeg successfully installed and configured for this addon.\nFFmpeg will be used from: {path}",
    "ffmpeg.install_fail_message": "Failed to download/install FFmpeg: {error}",
    "ffmpeg.manual_install_message_linux_mac": "FFmpeg not found.\nPlease install it using your system's package manager (e.g., sudo apt install ffmpeg, brew install ffmpeg) and restart Anki.",
    "ffmpeg.config_after_download_fail": "FFmpeg was downloaded, but an error occurred while configuring it for use.\nCheck the addon or console logs for details.",
    "ffmpeg.using_system_ffmpeg": "Using FFmpeg found in the system PATH: {path}",
    "ffmpeg.using_addon_ffmpeg": "Using FFmpeg from the addon's folder: {path}",
    "ffmpeg.failed_to_locate": "Could not locate or configure FFmpeg. Media processing features will be disabled.",
    "ffmpeg.error_creating_vendor_dir": "Error creating folder for FFmpeg '{path}': {error}",
    "ffmpeg.zip_file_error": "Error processing the FFmpeg ZIP file: {error}",
    "ffmpeg.extraction_error_no_bin": "Could not find the 'bin' folder inside the extracted FFmpeg archive.",
    "ffmpeg.extraction_exe_missing": "Executable '{exe_name}' not found in the FFmpeg 'bin' folder.",
    "general.button.select_folder": "Select Folder",
    "general.button.cancel": "Cancel",
    "general.error.title": "Error",
    "general.warning.title": "Warning",
    "general.confirmation.title": "Confirmation",
    "general.info.title": "Information",
    "general.dependency_module_not_loaded": "Module '{module_name}' not loaded.",
    "general.log.stop_requested_generic": "Stop requested for {operation_name}...",
    "general.log.op_name_split": "splitting",
    "general.log.op_name_images": "image conversion",
    "general.log.op_name_generation": "subtitle generation",
    "general.log.op_name_translation": "translation",
    "general.dialog.close_confirmation_title": "Process(es) in Progress",
    "general.dialog.close_confirmation_message": "{thread_names} process(es) are running. Do you want to stop them and close?",
    "general.log.waiting_for_thread_generic": "Waiting for {thread_name} to finish (up to 3s)...",
    "general.log.thread_not_finished_warning_generic": "WARNING: {thread_name} thread did not finish in time.",
    "general.anki_media_dir_unavailable_warning": "WARNING: Anki's collection.media directory is not accessible. The option to save directly to it will be disabled.",
    "general.na_value": "N/A",
    "all_files_filter": "All files (*.*)",
    "selected_log_suffix": "selected",
    "auto_found_log_suffix": "auto-found",
    "path_not_valid_log": "path is not a valid file",
    "subs_translation_count_mismatch_warning_log": "WARNING: Number of subtitles ({subs_count}) and translations ({trans_count}) differs. Check synchronization.",
    "set_to_log_suffix": "set to",
    "op_interrupted_status": "interrupted",
    "op_completed_status": "completed",
    "and_joiner_for_thread_names": " and ",
    "log.addon_started": "Advanced Media Splitter '{addon_name}' Started.",
    "process.log.using_config_file_location": "Using config file: {path}",
    "process.log.default_output_folder_media": "Default output folder for media: {path}",
    "process.log.default_output_folder_images": "Default output folder for images: {path}",
    "process.checkbox.generate_translation": "Also generate translation to:",

    # --- Media Downloader Tab ---
    "dl.group.url": "1. Enter URL (YouTube, Facebook, Instagram, TikTok, etc.)",
    "dl.placeholder.url": "Paste media URL here",
    "dl.button.analyze": "Analyze Link",
    "dl.group.save": "2. Choose Where to Save",
    "dl.radio.desktop": "Save to Desktop",
    "dl.radio.custom_path": "Choose another location...",
    "dl.placeholder.no_path": "No location selected",
    "dl.button.browse": "Browse...",
    "dl.group.auth": "3. Authentication (for sites requiring login)",
    "dl.radio.no_auth": "None (default)",
    "dl.radio.cookie": "Use cookies file (.txt)",
    "dl.placeholder.no_cookie": "No file selected",
    "dl.label.cookie_help": "<b>How to get the cookies file:</b><br>1. Install the <b>'Cookie-Editor'</b> extension in Chrome/Firefox.<br>2. In your browser, <b>log in to the site</b> (e.g., TikTok).<br>3. With the site open, click the extension icon (🍪).<br>4. In the popup, click <b>'Export'</b> <img src='{icon_path}' style='vertical-align: middle; height: 16px;'>.<br>5. Open Notepad, paste the text, and save as a .txt file.",
    "dl.group.format": "4. Choose Format and Options",
    "dl.checkbox.subs": "Download subtitles (.srt) with video",
    "dl.label.langs": "Languages:",
    "dl.placeholder.langs": "Ex: en or en-US",
    "dl.tooltip.langs": "Use 'en' for English. If the video has US English subs, type 'en-US'.",
    "dl.tab.video": "Video (MP4)",
    "dl.tab.audio": "Audio (MP3)",
    "dl.group.queue": "5. Download Queue",
    "dl.table.url": "URL",
    "dl.table.status": "Status",
    "dl.table.progress": "Progress",
    "dl.button.start_queue": "Start Queue",
    "dl.button.clear_completed": "Clear Completed",
}