
translations = {
    "preview.button.clear_all": "Limpar Tudo",
    "preview.confirm.clear_all.title": "Confirmar Limpeza",
    "preview.confirm.clear_all.message": "Você tem certeza que deseja excluir todos os {count} arquivos de mídia gerados e limpar a lista? Esta ação não pode ser desfeita.",
    "log.session_data_loaded": "{count} itens da sessão anterior foram carregados.",
    "tab.preview.title": "Pré-visualização",
    "preview.group.file_list.title": "Arquivos Gerados",
    "preview.button.refresh": "Atualizar Lista",
    "preview.group.player.title": "Player",
    "preview.label.subtitle": "Legenda:",
    "preview.info.no_items": "Nenhum item de mídia foi gerado ainda.",
    "preview.info.click_item": "Clique em um item da lista para pré-visualizar.",
    "preview.action.delete": "Excluir",
    "preview.speed.slow": "0.5x",
    "preview.speed.normal": "1x (Normal)",
    "preview.speed.fast": "1.5x",
    "preview.speed.very_fast": "2x",
    "preview.checkbox.show_translation": "Mostrar Tradução",
    "tab.subs_and_time.title": "Legendas e Tempo",
    "process.group.generation.title": "Gerar Legendas (com API Online)",
    "process.info.api_key_instructions": 'Crie uma conta gratuita em <a href="https://www.assemblyai.com/">AssemblyAI</a> e pegue sua chave de API em <a href="https://www.assemblyai.com/dashboard/api-keys">seu painel</a>.',
    "process.button.generate_subs": "Gerar Legendas do Áudio/Vídeo",
    "process.label.transcription_language": "Idioma da Legenda:",
    "process.label.api_key": "Chave de API (AssemblyAI):",
    "process.placeholder.api_key": "Cole sua chave de API gratuita aqui",
    "process.error.api_key_needed": "Por favor, insira uma chave de API para usar a geração de legendas online.",
    "process.error.media_file_needed_for_generation": "Selecione um arquivo de mídia primeiro para gerar legendas.",
    "process.warning.generation_running": "Processo de geração de legendas já em execução.",
    "process.log.generation_started": "Iniciando geração de legendas com API online. Isso pode demorar.",
    "process.status.generating_stopping": "Parada da geração solicitada...",
    "process.group.translation.title": "Traduzir Legendas (com API Online)",
    "process.button.translate_subs": "Traduzir Legenda Principal",
    "process.label.translation_language": "Idioma de Destino:",
    "process.error.no_subs_to_translate": "Carregue uma legenda principal primeiro para traduzir.",
    "process.log.translation_started": "Iniciando tradução da legenda. Isso pode demorar.",
    "transcription.starting_status": "Iniciando geração de legendas online...",
    "transcription.uploading": "Enviando arquivo de mídia para a API...",
    "transcription.transcribing": "API está transcrevendo o áudio... Por favor, aguarde.",
    "transcription.polling": "Aguardando resultado da API...",
    "transcription.interrupted_log": "Geração de legendas interrompida.",
    "transcription.error_log": "ERRO ao gerar legendas online: {error}",
    "transcription.finalize_prefix": "Geração de legendas {status}.",
    "transcription.finalize_showInfo_success": "{prefix}\nArquivo de legenda gerado e carregado:\n{path}",
    "transcription.finalize_showInfo_fail": "{prefix}\nNenhum arquivo de legenda foi gerado.",
    "translation.performing": "Traduzindo item {current}/{total}...",
    "translation.finalize_prefix": "Tradução {status}.",
    "translation.finalize_showInfo_success": "{prefix}\nArquivo de legenda traduzido gerado e carregado:\n{path}",
    "translation.finalize_showInfo_fail": "{prefix}\nNenhum arquivo de legenda traduzido foi gerado.",
    "dialog.title": f"Divisor de Mídia Avançado ({__name__.split('.')[0]})",
    "dialog.language_label": "Idioma:",
    "tab.process.title": "Entrada e Processamento",
    "tab.images.title": "Gerar Imagens de Vídeos",
    "tab.anki_export.title": "Exportação para Anki",

    "tab.downloader.title": "Baixador de Mídia",
    "process.group.files.title": "Arquivos de Entrada e Saída",
    "process.label.media_file": "Arquivo de Mídia (Áudio/Vídeo):",
    "process.placeholder.media_file": "Caminho para o arquivo de áudio ou vídeo",
    "process.button.open_media": "Abrir Mídia",
    "process.label.main_subtitle": "Legenda (SRT, VTT, etc.):",
    "process.placeholder.main_subtitle": "Caminho para o arquivo de legenda",
    "process.button.open_subtitle": "Abrir Legenda",
    "process.label.translation_subtitle": "Tradução (Legenda - Opcional):",
    "process.placeholder.translation_subtitle": "Caminho para o arquivo de legenda da tradução",
    "process.button.open_translation": "Abrir Tradução",
    "process.label.output_folder_media": "Pasta de Saída (mídia processada):",
    "process.button.select_output_folder": "Selecionar Pasta",
    "process.checkbox.direct_to_collection_media": "Enviar diretamente para collection.media do Anki",
    "process.label.output_format": "Formato de Saída:",
    "process.format.mp3": "MP3 (áudio)",
    "process.format.mp4": "MP4 (vídeo)",
    "process.format.webm": "WebM (vídeo)",
    "process.group.offset.title": "Ajuste de Tempo (Legenda Principal)",
    "process.label.offset_seconds": "Segundos (ex: 0.5 adianta, -0.3 atrasa):",
    "process.button.apply_offset_save_srt": "Aplicar Ajuste e Salvar Legenda",
    "process.group.time_limit.title": "Limite por Legendas (Opcional)",
    "process.checkbox.limit_time_range": "Limitar processamento a um intervalo de tempo",
    "process.label.time_limit_from": "De:",
    "process.label.time_limit_to": "Até:",
    "process.placeholder.time_limit": "HH:MM:SS",
    "process.log.time_limit_applied": "INFO: Limite de tempo aplicado. Processando {count} de {total} legendas no intervalo de {start} a {end}.",
    "process.group.single_clip.title": "Corte Único (com Legenda)",
    "process.button.single_clip": "Cortar e Salvar Clipe",
    "process.log.single_clip_started": "Iniciando corte único para o arquivo '{filename}'...",
    "process.log.single_clip_success": "SUCESSO: Clipe único salvo em '{path}'.",
    "process.log.single_clip_and_srt_success": "SUCESSO: Clipe único e legenda correspondente salvos em '{path}'.",
    "process.log.single_clip_srt_error": "AVISO: Clipe de vídeo foi salvo, mas falhou ao criar o arquivo de legenda: {error}",
    "process.log.single_clip_error": "ERRO ao criar clipe único para '{filename}'. FFmpeg stderr: {stderr}",
    "process.error.invalid_time_range": "Intervalo de tempo inválido. O tempo final deve ser maior que o inicial.",
    "process.group.main_processing.title": "Processamento Principal (Dividir Mídia)",
    "process.checkbox.adjust_cuts_to_silence": "Ajustar cortes para pausas no áudio (mais preciso)",
    "process.log.silence_detection_started": "Iniciando detecção de silêncio no áudio. Isso pode levar um momento...",
    "process.log.silence_detection_finished": "Detecção de silêncio concluída. {count} pausas encontradas.",
    "process.log.silence_detection_failed": "AVISO: Falha na detecção de silêncio. Os cortes serão feitos nos tempos exatos da legenda. Erro: {error}",
    "process.button.split_media": "Dividir Mídia Conforme Legendas",
    "process.button.stop_processing": "Parar Processo",
    "process.label.time_remaining_prefix": "Tempo restante:",
    "process.label.status_ready": "Pronto.",
    "process.label.status_calculating": "Calculando...",
    "process.group.log.title": "Log Detalhado (Processamento de Mídia)",
    "process.info.ffmpeg_not_found": "FFmpeg não encontrado. Verifique a instalação ou permita o download pelo addon.",
    "process.warning.process_running": "Processo de divisão em execução.",
    "process.error.invalid_media_file": "Arquivo de mídia inválido.",
    "process.error.no_main_subtitle": "Nenhuma legenda principal carregada.",
    "process.error.output_folder_invalid": "Pasta de saída inválida ou não pôde ser criada:\n{path}\nErro: {error}",
    "process.log.using_default_output_folder": "Pasta de saída não definida, usando padrão: {path}",
    "process.log.split_started": "Iniciando divisão de mídia (formato: {format}). Total de {count} itens.",
    "process.status.stopping": "Parada solicitada...",
    "process.dialog.offset_srt.no_subs_loaded": "Nenhuma legenda principal carregada.",
    "process.dialog.offset_srt.invalid_offset_value": "Segundos de ajuste inválidos.",
    "process.dialog.offset_srt.output_folder_needed": "Defina uma pasta de saída primeiro (na aba 'Entrada e Processamento').",
    "process.dialog.offset_srt.error_creating_folder": "Pasta de saída para legenda ajustada é inválida ou não pôde ser criada:\n{path}\nErro: {error}",
    "process.dialog.offset_srt.success_title": "Ajuste Salvo",
    "process.dialog.offset_srt.success_message": "Legendas principais {action_desc} e salvas em:\n{path}",
    "process.dialog.offset_srt.action_unchanged": "inalteradas",
    "process.dialog.offset_srt.action_advanced": "adiantadas",
    "process.dialog.offset_srt.action_delayed": "atrasadas",
    "process.dialog.offset_srt.error_saving_title": "Erro ao Salvar Legenda Ajustada",
    "process.dialog.offset_srt.error_saving_message": "Não foi possível salvar o arquivo de legenda: {error}",
    "process.dialog.offset_srt.log_saving_to_original_folder": "Legenda ajustada será salva na pasta da legenda original: {path}",
    "process.dialog.offset_srt.log_suffix_original_srt_undefined_fallback": " (para a legenda ajustada, pois a legenda original não estava definida ou era inválida).",
    "process.dialog.offset_srt.log_fallback_to_main_output": "A legenda original não está carregada ou é inválida. A legenda ajustada será salva na pasta de saída principal: {path}",
    "process.dialog.offset_srt.info_fallback_to_main_output": "A legenda original não está carregada ou o caminho do arquivo é inválido.\nO arquivo de legenda ajustado será salvo na pasta de saída principal:\n{path}",
    "process_starting_status": "Iniciando processamento...",
    "preparing_items_status": "Preparando {count} itens...",
    "split_interrupted_log": "Divisão interrompida.",
    "processing_item_status": "Processando {current}/{total} (ID:{id}) - {percent}%",
    "skipped_item_log": "AVISO: ID {id} pulada (sem texto ou tempo inválido).",
    "reencoding_to_mp4_log": "INFO: Re-encodificando para MP4 (ID {id}): {filename}",
    "reencoding_to_webm_log": "INFO: Re-encodificando para WebM (ID {id}): {filename}",
    "unsupported_ext_for_split_log": "ERRO: Extensão de arquivo não suportada para divisão: {ext}",
    "file_created_success_log": "SUCESSO: {filename} criado.",
    "file_and_srt_created_success_log": "SUCESSO: {filename} e legenda .srt criados.",
    "process.log.srt_creation_failed": "AVISO: Arquivo de mídia criado, mas falha ao salvar legenda .srt para ID {id}: {error}",
    "ffmpeg_error_log": "ERRO FFmpeg (ID {id}, {ext}): {filename}. Stderr: {stderr}",
    "ffmpeg_reencode_fail_warning_log": "AVISO: Falha no re-encode para {ext} (ID {id}). O arquivo original pode ter problemas ou codecs incompatíveis.",
    "ffmpeg_general_error_log": "ERRO FFmpeg geral (ID {id}, {ext}): {error}",
    "split_finalize_prefix": "Divisão {status}.",
    "files_created_log_suffix": "{count} arquivos de mídia criados.",
    "split_finalize_detailed_status": "{prefix} {files_count} arquivos. {items_attempted}/{total_initial} processados ({percent}%).",
    "split_finalize_all_created_status": "{prefix} Todos {count} arquivos criados (100%).",
    "split_finalize_showInfo_success": "{prefix}\n{count} arquivos em:\n{path}",
    "split_finalize_showInfo_no_files": "{prefix}\nNenhum arquivo de mídia criado.",
    "applying_offset_log": "Aplicando ajuste de {offset_s}s ({offset_ms}ms) à legenda principal.",
    "adjusted_subs_default_filename_stem": "legendas_ajustadas",
    "subs_filename_suffix": "legendas",
    "adjusted_srt_filename_suffix": "ajustado",
    "adjusted_subs_saved_log": "Legendas principais ajustadas salvas em: {path}",
    "images.group.title": "Gerar Imagens",
    "images.group.from_source.title": "Método 1: Do Vídeo Original (Rápido e Recomendado)",
    "images.info.generate_from_source": "Este método usa o arquivo de vídeo principal da aba 'Entrada' e as legendas carregadas para gerar rapidamente uma imagem para cada legenda. É a forma mais eficiente se você precisa de áudio (MP3) e imagens.",
    "images.button.generate_from_source": "Gerar Imagens do Vídeo Original",
    "images.group.from_split_videos.title": "Método 2: Dos Clipes de Vídeo Divididos",
    "images.info.source_videos_intro": "Este método usa os vídeos (.mp4, .webm) já gerados na aba 'Entrada e Processamento' para criar imagens .jpg.",
    "images.info.output_destination_prefix": "As imagens geradas serão salvas em:",
    "images.checkbox.direct_to_collection_media": "Enviar imagens geradas diretamente para collection.media do Anki",
    "images.button.convert_videos": "Converter Vídeos Divididos para Imagens",
    "images.button.stop_conversion": "Parar Geração de Imagens",
    "images.label.status_ready": "Pronto.",
    "images.group.log.title": "Log Detalhado (Geração de Imagens)",
    "images.log.using_default_media_folder": "Pasta de saída de mídia não definida, usando padrão: {path}",
    "images.error.media_folder_invalid": "A pasta de saída de mídia '{path}' é inválida.",
    "images.info.no_videos_found": "Nenhum arquivo de vídeo .mp4 ou .webm encontrado na pasta '{path}' para converter.",
    "images.info.no_subtitles_data_for_videos": "Nenhum dado da aba 'Entrada e Processamento' encontrado. Processe mídias primeiro para gerar vídeos.",
    "images.info.no_valid_videos_from_processing": "Nenhum arquivo de vídeo .mp4 ou .webm válido foi encontrado {source} para converter.",
    "images.source_description.processed_items": "dos itens processados na primeira aba",
    "images.error.cannot_create_images_folder": "Não foi possível criar/acessar a pasta de imagens '{path}': {error}",
    "images.log.conversion_started": "Iniciando conversão de {count} vídeos para imagens .jpg em {path}.",
    "images.log.conversion_started_from_processed": "Iniciando conversão de {count} vídeos (da aba de processamento) para imagens .jpg em {path}.",
    "images.log.generation_from_source_started": "Iniciando geração de imagens a partir do vídeo de origem para {count} legendas.",
    "images.status.stopping": "Parada solicitada...",
    "images.finalize.info_success": "{status_text}\nSalvas em: {path}",
    "images.finalize.info_no_images": "{status_text}\nNenhuma imagem foi gerada.",
    "image_conversion_starting_status": "Iniciando geração de imagens...",
    "preparing_videos_status": "Preparando {count} vídeos...",
    "preparing_subtitles_status": "Preparando {count} legendas para geração de imagens...",
    "image_conversion_interrupted_log": "Geração de imagens interrompida.",
    "converting_video_status": "Convertendo {filename} ({current}/{total})",
    "generating_image_from_source_status": "Gerando imagem para legenda {current}/{total}",
    "image_created_success_log": "SUCESSO: Imagem '{filename}' criada.",
    "ffmpeg_run_but_image_not_created_log": "ERRO: FFmpeg executado, mas '{filename}' não criada ou vazia.",
    "ffmpeg_error_converting_image_log": "ERRO FFmpeg ao converter '{filename}'",
    "general_error_converting_image_log": "ERRO geral ao converter '{filename}': {error}",
    "image_conversion_finalize_prefix": "Geração de imagens {status}.",
    "image_conversion_finalize_log": "{prefix} {created_count}/{total_count} imagens geradas.",
    "image_conversion_finalize_status_ui": "{prefix} {count} imagens geradas.",
    "anki_export.group.title": "Opções de Exportação para o Anki",
    "anki_export.label.deck": "Deck:",
    "anki_export.label.note_type": "Tipo de Nota:",
    "anki_export.label.media_field": "Campo de Mídia (Áudio/Vídeo):",
    "anki_export.label.subtitle_field": "Campo da Legenda Principal:",
    "anki_export.label.translation_field": "Campo de Tradução:",
    "anki_export.label.image_field": "Campo de Imagens:",
    "anki_export.group.media_files_anki.title": "Arquivos de Mídia para Exportação",
    "anki_export.label.source_folder": "Pasta de Origem:",
    "anki_export.placeholder.source_folder": "Padrão: arquivos processados nesta sessão",
    "anki_export.button.select_source_folder": "Selecionar Pasta...",
    "anki_export.button.clear_source_folder": "Limpar",
    "anki_export.button.list_media_files": "Listar Arquivos da Origem",
    "anki_export.button.add_to_anki": "Adicionar Itens Listados ao Anki",
    "anki_export.log.media_folder_not_defined": "Pasta de saída de mídia não definida.",
    "anki_export.log.media_folder_invalid": "Pasta de mídia '{path}' não é válida.",
    "anki_export.log.no_media_files_found": "Nenhum arquivo de mídia (.mp3, .mp4, .webm) encontrado em:\n{path}",
    "anki_export.log.files_listed_for_export": "{count} arquivos de mídia listados para exportação Anki de '{source}'.",
    "anki_export.log.source.session": "sessão atual",
    "anki_export.log.source.folder": "pasta selecionada",
    "anki_export.error.anki_collection_unavailable": "Coleção Anki não disponível.",
    "anki_export.error.missing_selections": "Selecione Deck, Tipo de Nota, Campo de Mídia e Campo de Legenda Principal.",
    "anki_export.error.note_type_not_found": "Tipo de Nota ID {model_id} não encontrado.",
    "anki_export.error.field_not_in_model": "Campo de {field_desc} '{field_name}' não existe no Tipo de Nota '{model_name}'.",
    "anki_export.error.field_desc.media": "Mídia",
    "anki_export.error.field_desc.main_subtitle": "Legenda Principal",
    "anki_export.error.field_desc.translation": "Tradução",
    "anki_export.error.field_desc.image": "Imagem",
    "anki_export.error.field_not_selected": "Campo de {field_desc} não selecionado.",
    "anki_export.confirm.combined_fields_title": "Campos Combinados",
    "anki_export.confirm.combined_fields_message": "Alguns campos selecionados são os mesmos. O conteúdo será combinado nesses campos usando '<br>' como separador. Continuar?",
    "anki_export.progress.adding_notes": "Adicionando notas ao Anki...",
    "anki_export.progress.adding_note_item": "Adicionando {current}/{total}: {filename}",
    "anki_export.info.notes_added_success": "{count} notas adicionadas a '{deck_name}'.",
    "anki_export.info.no_notes_added": "Nenhuma nota adicionada. Verifique o log.",
    "anki_export.info.addition_cancelled": "Adição cancelada. {count} notas adicionadas antes.",
    "anki_export.log.completed_anki_add": "Concluída adição ao Anki: {count} notas.",
    "anki_export.log.no_processed_items_for_export": "Nenhum item de mídia processado (das legendas atuais) disponível para exportação.",
    "anki_export.info.no_processed_items_for_export_title": "Nenhum Item para Exportar",
    "anki_export.warning.no_subtitles_loaded_for_export": "Nenhuma legenda principal carregada. Não há itens para processar para exportação.",
    "anki_export.log.no_subtitles_loaded_for_listing": "Nenhuma legenda carregada para listar arquivos de mídia processados.",
    "anki_export.log.no_media_files_processed_in_session": "Nenhum arquivo de mídia gerado/processado na sessão atual.",
    "anki_export.log.processed_media_files_header": "Arquivos de mídia processados na sessão atual (em: {folder_path}, {count} itens):\n",
    "failed_to_copy_main_media_log": "Falha ao copiar mídia principal para Anki: {filename}",
    "error_adding_main_media_log": "Erro ao adicionar mídia principal '{filename}':{error}",
    "failed_to_copy_image_log": "Falha ao copiar imagem para Anki: {filename}",
    "error_adding_image_log": "Erro ao adicionar imagem '{filename}': {error}",
    "error_adding_note_log": "Erro ao adicionar nota para '{filename}':{error}",
    "error_cleaning_orphan_media_log": "Erro ao limpar mídia órfã '{filename}': {error}",
    "error_cleaning_orphan_image_log": "Erro ao limpar imagem órfã '{filename}': {error}",
    "media_files_in_folder_log_header": "Arquivos de mídia em {path} ({count} itens):\n",
    "ffmpeg.ask_download_title": "FFmpeg Não Encontrado / FFmpeg Not Found",
    "ffmpeg.ask_download_message": (
        "<p>{us_flag_html}FFmpeg was not found on your system or in this addon's folder.<br>"
        "It is essential for processing audio and video files.</p>"
        "<p>{us_flag_html}Do you want to automatically download and install FFmpeg (~80MB) into this addon's folder?<br>"
        "(Recommended for Windows users. Linux/macOS users usually install it via their system's package manager.)</p>"
        "<hr>"
        "<p>{br_flag_html}O FFmpeg não foi encontrado no seu sistema ou na pasta deste addon.<br>"
        "Ele é essencial para processar arquivos de áudio e vídeo.</p>"
        "<p>{br_flag_html}Deseja baixar e instalar automaticamente o FFmpeg (~80MB) na pasta deste addon?<br>"
        "(Recomendado para usuários Windows. Usuários Linux/macOS geralmente instalam via gerenciador de pacotes do sistema.)</p>"
    ),
    "ffmpeg.download_cancelled_message_addon": (
        "<p>{us_flag_html}FFmpeg download cancelled by user. Media processing features may not be available or may fail.</p>"
        "<hr>"
        "<p>{br_flag_html}Download do FFmpeg cancelado pelo usuário. Funcionalidades de processamento de mídia podem não estar disponíveis ou falhar.</p>"
    ),
    "ffmpeg.downloading_message": "Downloading FFmpeg... \nBaixando FFmpeg...",
    "ffmpeg.download_progress_label": "Downloading FFmpeg: \nBaixando FFmpeg: {percent}%",
    "ffmpeg.download_cancelled_by_user": "Download do FFmpeg cancelado pelo usuário.",
    "ffmpeg.download_failed_with_error": "Falha no download do FFmpeg: {error}",
    "ffmpeg.extracting_message": "FFmpeg baixado. Descompactando e configurando...",
    "ffmpeg.extraction_failed": "Falha ao descompactar o FFmpeg: {error}",
    "ffmpeg.install_success_message": "FFmpeg instalado e configurado com sucesso para este addon.\nO FFmpeg será usado a partir de: {path}",
    "ffmpeg.install_fail_message": "Falha ao baixar/instalar FFmpeg: {error}",
    "ffmpeg.manual_install_message_linux_mac": "FFmpeg não encontrado.\nPor favor, instale-o usando o gerenciador de pacotes do seu sistema (ex: sudo apt install ffmpeg, brew install ffmpeg) e reinicie o Anki.",
    "ffmpeg.config_after_download_fail": "FFmpeg foi baixado, mas ocorreu um erro ao configurá-lo para uso.\nVerifique os logs do addon ou console para detalhes.",
    "ffmpeg.using_system_ffmpeg": "Usando FFmpeg encontrado no PATH do sistema: {path}",
    "ffmpeg.using_addon_ffmpeg": "Usando FFmpeg da pasta do addon: {path}",
    "ffmpeg.failed_to_locate": "Não foi possível localizar ou configurar o FFmpeg. Funcionalidades de processamento de mídia estarão desabilitadas.",
    "ffmpeg.error_creating_vendor_dir": "Erro ao criar pasta para FFmpeg '{path}': {error}",
    "ffmpeg.zip_file_error": "Erro ao processar o arquivo ZIP do FFmpeg: {error}",
    "ffmpeg.extraction_error_no_bin": "Não foi possível encontrar a pasta 'bin' dentro do arquivo FFmpeg extraído.",
    "ffmpeg.extraction_exe_missing": "Executável '{exe_name}' não encontrado na pasta 'bin' do FFmpeg.",
    "general.button.select_folder": "Selecionar Pasta",
    "general.button.cancel": "Cancelar",
    "general.error.title": "Erro",
    "general.warning.title": "Atenção",
    "general.confirmation.title": "Confirmação",
    "general.info.title": "Informação",
    "general.dependency_module_not_loaded": "Módulo '{module_name}' não carregado.",
    "general.log.stop_requested_generic": "Parada da {operation_name} solicitada...",
    "general.log.op_name_split": "divisão",
    "general.log.op_name_images": "conversão de imagens",
    "general.log.op_name_generation": "geração de legendas",
    "general.log.op_name_translation": "tradução",
    "general.dialog.close_confirmation_title": "Processo(s) em Andamento",
    "general.dialog.close_confirmation_message": "Processo(s) de {thread_names} em execução. Deseja pará-lo(s) e fechar?",
    "general.log.waiting_for_thread_generic": "Aguardando finalização de {thread_name} (até 3s)...",
    "general.log.thread_not_finished_warning_generic": "AVISO: Thread de {thread_name} não finalizou a tempo.",
    "general.anki_media_dir_unavailable_warning": "AVISO: Diretório collection.media do Anki não está acessível. A opção de salvar diretamente nele será desabilitada.",
    "general.na_value": "N/D",
    "all_files_filter": "Todos os arquivos (*.*)",
    "selected_log_suffix": "selecionada",
    "auto_found_log_suffix": "automática encontrada",
    "path_not_valid_log": "caminho não é um arquivo válido",
    "subs_translation_count_mismatch_warning_log": "AVISO: Núm. legendas ({subs_count}) e traduções ({trans_count}) difere. Verifique sincronia.",
    "set_to_log_suffix": "definida para",
    "op_interrupted_status": "interrompida",
    "op_completed_status": "concluída",
    "and_joiner_for_thread_names": " e ",
    "log.addon_started": "Divisor de Mídia Avançado '{addon_name}' Iniciado.",
    "process.log.using_config_file_location": "Usando arquivo de configuração: {path}",
    "process.log.default_output_folder_media": "Pasta de saída padrão para mídia: {path}",
    "process.log.default_output_folder_images": "Pasta de saída padrão para imagens: {path}",
    "process.checkbox.generate_translation": "Gerar também tradução para:",
    "anki_export.checkbox.use_external_folder": "Usar arquivos de uma pasta específica (se desmarcado, usa os da sessão atual)",
    "anki_export.group.media_files_anki.title": "Arquivos de Mídia para Exportação",
    "anki_export.group.source_files.title": "Fonte dos Arquivos",
    "anki_export.radio.use_session_files": "Usar arquivos da sessão atual (padrão)",
    "anki_export.radio.use_external_folder": "Usar pasta externa",
    "anki_export.button.select_source_folder": "Selecionar Pasta...",
    "anki_export.button.list_media_files": "Listar Arquivos da Fonte",
}